services:
  - type: web
    name: job-board-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    rootDir: server
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static
    name: job-board-frontend
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
